/*--------------------------------------------------------------------
  This file is part of the han-iot-portfolio-Prototype-LoRaWAN-node.
  --------------------------------------------------------------------*/
/**
 * @file ThingsNetworkConfig.cpp
 * @brief Implementation of LoRaWAN communication services.
 *
 * @details
 * This module implements the communication workflow between
 * the prototype node and The Things Network.
 *
 * Functions provided by this module:
 * - Device initialization
 * - OTAA network joining
 * - Payload creation
 * - Uplink transmission
 *
 * Sensor data generated by the prototype is transmitted to the
 * LoRaWAN network for monitoring of domestic rainwater buffering
 * systems.
 */
#include "ThingsNetworkConfig.h"

const char *appEui = "1000000000000000";
const char *appKey = "55E00FB8A088136213586D2295F764B2";

TheThingsNetwork ttn(loraSerial, debugSerial, freqPlan);
myPayloadEncoder encoder;   // Encoder object

void joinNetwork_and_debug()
{
	loraSerial.begin(57600);
    debugSerial.begin(9600);
	// Wait a maximum of 10s for Serial Monitor 
    while (!debugSerial && millis() < 10000);
	debugSerial.println("-- STATUS");
    ttn.showStatus();
    debugSerial.println("-- JOIN");
    ttn.setADR(true);   // Let network optimize data rate
    ttn.join(appEui, appKey);
}

void build_and_sendUplink()
{
    encoder.setSensorValue(FLOW_METER, flow_mL);             // Set variable in encoder object.
	encoder.setSensorValue(LEVEL_METER, level_cM);           // Set variable in encoder object.
    encoder.setSensorValue(BATTERY_VOLTAGE, battery_cV);   // Set variable in encoder object.
    encoder.composePayload();
	ttn.sendBytes(encoder.getPayload(), encoder.getPayloadSize(), 1);   // FPort=1
    flow_mL = 0; // reset the folwmeter pulses counter
}
